name       : snappy
version    : 1.1.3
release    : 1
source     :
    - https://github.com/google/snappy/releases/download/1.1.3/snappy-1.1.3.tar.gz : 2f1e82adf0868c9e26a5a7a3115111b6da7e432ddbac268a7ca2fae2a247eef3
license    : BSD-3
summary    : Snappy is a compression/decompression library.
description: |
    Snappy is a compression/decompression library. It does not aim for maximum compression, or compatibility with any other compression library; instead, it aims for very high speeds and reasonable compression.
libsplit: no
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
